server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /artist-images/ {
        proxy_pass http://artist-images:8080/;
    }

    location /deezer-api/ {
        proxy_pass https://api.deezer.com/;
        proxy_ssl_server_name on;
        proxy_set_header Host api.deezer.com;
    }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
}