// Curated genre list based on common music metadata conventions.
// Covers the most widely used genres without the obscure/legacy ID3v1 noise.
export const GENRES = [
  'Acoustic',
  'Alternative',
  'Ambient',
  'Blues',
  'Classical',
  'Country',
  'Dance',
  'Disco',
  'Drum & Bass',
  'Easy Listening',
  'Electronic',
  'Experimental',
  'Folk',
  'Funk',
  'Gospel',
  'Hip-Hop',
  'House',
  'Indie',
  'Instrumental',
  'Jazz',
  'Latin',
  'Lounge',
  'Metal',
  'New Age',
  'New Wave',
  'Opera',
  'Pop',
  'Post-Rock',
  'Progressive Rock',
  'Punk',
  'R&B',
  'Reggae',
  'Rock',
  'Singer-Songwriter',
  'Ska',
  'Soul',
  'Soundtrack',
  'Techno',
  'Trance',
  'World',
]
